# Generated by Django 3.2.5 on 2021-07-13 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=20)),
                ('acntnumber', models.IntegerField(default=None)),
                ('email', models.EmailField(default=None, max_length=20)),
                ('MobNumber', models.CharField(default=None, max_length=10)),
                ('balance', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='fromuser', to='empcrud.employee')),
                ('to_acnt', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='touser', to='empcrud.employee')),
            ],
        ),
    ]
