# Generated by Django 3.2.5 on 2021-07-13 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empcrud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='name',
            new_name='name1',
        ),
    ]
