# Generated by Django 3.2.5 on 2021-07-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empcrud', '0002_rename_name_transaction_name1'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frm', models.CharField(default=None, max_length=20)),
                ('to', models.CharField(default=None, max_length=20)),
                ('money', models.DecimalField(decimal_places=2, default=None, max_digits=100)),
                ('date', models.CharField(default=None, max_length=20)),
            ],
        ),
    ]
