# Generated by Django 3.2.5 on 2021-07-13 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empcrud', '0003_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='name1',
            new_name='from_acnt',
        ),
    ]
