# Generated by Django 3.2.5 on 2021-07-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empcrud', '0004_rename_name1_transaction_from_acnt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(default=None, max_length=30),
        ),
    ]
